### ISSUE TITLE
Add fallback support

### ISSUE THREAD

**Issue by sunng87** [sunng87/diehard#4]
We can now specify a fallback value/handler for retry block in failsafe 0.9.x

**Comment by sunng87** [comment]
released in 0.3.0

**Comment by dhruvbhatia** [comment]
Thanks so much for implementing this!

Quick q re: the signature, the [readme suggests the  `:fallback` fn returns `[exception value] arguments`](https://github.com/sunng87/diehard#fallback), but I seem to be getting `[nil exception]` instead (aka the `exception` is actually the second argument and the first argument always returns `nil`).

The readme states the return argument other than `exception` is meant to be the `value` of the previous attempt - but wouldn't this always return `nil` given we'd never hit the fallback criteria if the previous attempt returned a value rather than an exception?

**Comment by sunng87** [comment]
Good catch, @dhruvbhatia . That's a mistake in documentation. The first argument is return value, which is consistent with `retry-if`.

Because you can configure retry criteria that not only will exception cause retry, but also some return value that matches your criteria.

**Comment by dhruvbhatia** [comment]
Thanks for the quick response - that makes sense. 👍

**Comment by vendethiel** [comment]
Hey,
the fallback code uses `when-let (:fallback`, which means fallback falsy values, such as `nil` or `false`, can't be used (they'll be silently ignored).
This is either a bug, or something that could be documented. What do you think?

**Comment by sunng87** [comment]
@vendethiel it sounds more like a bug. We should fix it by wrapping a `(some?)`

**Comment by sunng87** [comment]
Fixed in a3fa30f
